#!/usr/bin/env python3
"""Regenerate the autogen inventory section in docs/architecture/test-coverage.md.

Replaces only the content between AUTOGEN:INVENTORY markers — manual
sections (coverage table, gaps, patterns) are preserved.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

_OUT = Path("docs/architecture/test-coverage.md")
_START = "<!-- AUTOGEN:INVENTORY:START -->"
_END = "<!-- AUTOGEN:INVENTORY:END -->"


def _pytest_cmd() -> list[str]:
    probe = subprocess.run([sys.executable, "-m", "pytest", "--version"], capture_output=True)
    if probe.returncode == 0:
        return [sys.executable, "-m", "pytest"]
    binary = shutil.which("pytest")
    if binary:
        return [binary]
    raise RuntimeError("pytest not found on PATH or as a Python module")


def _collect() -> list[str]:
    result = subprocess.run(
        _pytest_cmd() + ["--co", "-q"],
        capture_output=True,
        text=True,
    )
    return (result.stdout + result.stderr).splitlines()


def _parse(lines: list[str]) -> list[tuple[str, str, int, int]]:
    by_file: dict[str, dict[str, set[str]]] = defaultdict(
        lambda: {"tests": set(), "classes": set()}
    )
    for line in lines:
        line = line.strip()
        if "::" not in line:
            continue
        parts = line.split("::")
        if len(parts) < 2:
            continue
        file_path = parts[0]
        if not file_path.endswith(".py"):
            continue
        by_file[file_path]["tests"].add("::".join(parts[1:]))
        if len(parts) >= 3:
            by_file[file_path]["classes"].add(parts[1])

    rows = []
    for file_path, data in by_file.items():
        name = Path(file_path).name
        module = re.sub(r"^test_", "", name)
        rows.append((name, module, len(data["tests"]), len(data["classes"])))

    return sorted(rows, key=lambda r: (-r[2], r[0]))


def _inventory_block(rows: list[tuple[str, str, int, int]], total: int) -> str:
    lines = [
        _START,
        "",
        f"## Inventory ({total} tests)",
        "",
        "Auto-generated by `python scripts/gen_test_coverage.py`. Do not edit manually.",
        "",
        "| Test file | Module under test | Tests | Classes |",
        "|---|---|---|---|",
    ]
    for name, module, tests, classes in rows:
        lines.append(f"| `{name}` | `{module}` | {tests} | {classes} |")
    lines += ["", _END]
    return "\n".join(lines)


def main() -> None:
    if not _OUT.exists():
        sys.exit(f"{_OUT} does not exist; create it manually with autogen markers first")
    current = _OUT.read_text(encoding="utf-8")
    if _START not in current or _END not in current:
        sys.exit(f"markers {_START} / {_END} not found in {_OUT}")

    raw = _collect()
    test_ids = [ln.strip() for ln in raw if "::" in ln and not ln.strip().startswith("=")]
    rows = _parse(test_ids)
    block = _inventory_block(rows, len(test_ids))

    pattern = re.compile(re.escape(_START) + r".*?" + re.escape(_END), re.DOTALL)
    updated = pattern.sub(block, current)
    _OUT.write_text(updated, encoding="utf-8")
    print(f"Updated {_OUT} ({len(test_ids)} tests)")


if __name__ == "__main__":
    main()
