name: Run python script
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python scraper.py
        env: 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_CHATID: ${{ secrets.BOT_CHATID }}
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          API_KEY: ${{ secrets.API_KEY }}
          URLS: ${{ vars.URLS }}
          URLS_EVENTS: ${{ vars.URLS_EVENTS }}
          CHANNEL_URL: ${{ vars.CHANNEL_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          API_HASH: ${{ secrets.API_HASH }}
          API_ID: ${{ secrets.API_ID }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          AUTH_CODE: ${{ secrets.AUTH_CODE }}
